"""add period to todos, add habits and habit_checkins

Revision ID: 4edd159a9fd3
Revises: 9e352ccb5f8c
Create Date: 2026-10-01 20:27:25.740159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4edd159a9fd3'
down_revision: Union[str, Sequence[str], None] = '9e352ccb5f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_owner_id'), 'habits', ['owner_id'], unique=False)
    op.create_table('habit_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'period_key', name='uq_habit_period')
    )
    op.create_index(op.f('ix_habit_checkins_habit_id'), 'habit_checkins', ['habit_id'], unique=False)
    # server_default: mevcut satirlari doldurmak icin gerekli, sonra kaldiriliyor -
    # yeni satirlar zaten Python modelindeki default'u kullanacak
    op.add_column(
        'todos',
        sa.Column('period', sa.String(length=10), nullable=False, server_default='daily'),
    )
    op.alter_column('todos', 'period', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'period')
    op.drop_index(op.f('ix_habit_checkins_habit_id'), table_name='habit_checkins')
    op.drop_table('habit_checkins')
    op.drop_index(op.f('ix_habits_owner_id'), table_name='habits')
    op.drop_table('habits')
    # ### end Alembic commands ###
