"""add is_verified and token_version to users

Revision ID: 9e352ccb5f8c
Revises: 9862fa623697
Create Date: 2026-09-17 21:40:28.814032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e352ccb5f8c'
down_revision: Union[str, Sequence[str], None] = '9862fa623697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default: mevcut satirlari doldurmak icin gerekli (tablo bos
    # degil), sonra kaldiriliyor - yeni satirlar zaten Python modelindeki
    # default'u kullanacak
    op.add_column(
        'users',
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'users',
        sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('users', 'is_verified', server_default=None)
    op.alter_column('users', 'token_version', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
